{% set name = "fastprogress" %}
{% set version = "1.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a17d2b438890f838c048eefce32c4ded47197ecc8ea042cecc33d3deb8022f5

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - fastprogress

about:
  home: https://github.com/fastai/fastprogress
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A fast and simple progress bar for Jupyter Notebook and console.
  dev_url: https://github.com/fastai/fastprogress
  doc_url: https://github.com/fastai/fastprogress

extra:
  recipe-maintainers:
    - andersy005
